export const DEFAULT_COUNTRY = 'Philippines'

export const FALLBACK_VIBES = [
  'Beach & islands',
  'Mountain hiking',
  'City break',
  'Adventure sports',
  'Food & culture',
  'Solo travel',
  'Family trip',
  'Road trip',
  'Backpacking',
  'Island hopping',
  'Cultural immersion',
  'Wildlife & nature',
  'Photography spots',
  'Nightlife',
  'Wellness & spa',
  'Historical sites',
]

export const FALLBACK_COUNTRIES = [
  'Philippines',
  'Japan',
  'Thailand',
  'Vietnam',
  'Indonesia',
  'Malaysia',
  'Singapore',
  'South Korea',
  'China',
  'India',
  'Taiwan',
  'Hong Kong',
  'Cambodia',
  'Laos',
  'Myanmar',
  'Sri Lanka',
  'Nepal',
  'Maldives',
  'United Arab Emirates',
  'Qatar',
  'Saudi Arabia',
  'Oman',
  'Jordan',
  'Israel',
  'Turkey',
  'Egypt',
  'Morocco',
  'Kenya',
  'Tanzania',
  'South Africa',
  'France',
  'Spain',
  'Italy',
  'Greece',
  'Portugal',
  'United Kingdom',
  'Germany',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Czech Republic',
  'Poland',
  'Hungary',
  'Croatia',
  'Iceland',
  'Norway',
  'Sweden',
  'Finland',
  'Denmark',
  'Ireland',
  'USA',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'Peru',
  'Chile',
  'Colombia',
  'Australia',
  'New Zealand',
]

export const FALLBACK_BUDGETS = [
  'Under ₱10k',
  '₱10k – ₱30k',
  'Above ₱30k',
  'Free vlogs only',
]

export type TravelOptionCategory = 'country' | 'vibe' | 'budget'

export const TRAVEL_OPTION_SEEDS: Record<TravelOptionCategory, string[]> = {
  country: FALLBACK_COUNTRIES,
  vibe: FALLBACK_VIBES,
  budget: FALLBACK_BUDGETS,
}
